"""initial schema

Baseline for the 11 tables in api/models.py. Authored before a shared database existed —
until now the schema was built by create_all(), which creates MISSING tables and silently
ignores every column you alter, so a schema could look right and not be.

Two things worth knowing if you regenerate this:

* `server_default=sa.func.now()`, NOT sa.text('(CURRENT_TIMESTAMP)'). This was autogenerated
  against an empty SQLite file (no Postgres existed yet), and SQLite renders the default in
  its own dialect. Left as-is it does not match `func.now()` in the models, so every future
  --autogenerate would report a phantom diff on six timestamp columns forever. func.now()
  compiles per-dialect and matches the model exactly.

* sa.Enum(...) creates NATIVE Postgres types (channel, signupstatus, orderstate,
  fulfilmentmodel). Postgres does not drop a type when you drop the table using it, so the
  downgrade below removes them explicitly. Without that, downgrade-then-upgrade fails with
  "type already exists" — which is exactly when you least want a broken migration.


Revision ID: b9164af8a274
Revises: 
Create Date: 2026-08-27 18:49:55.040970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9164af8a274'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('wage_rate_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artisans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('craft', sa.String(length=80), nullable=True),
    sa.Column('cluster_id', sa.String(length=32), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('upi_id', sa.String(length=120), nullable=True),
    sa.Column('has_pan', sa.Boolean(), nullable=False),
    sa.Column('has_bank', sa.Boolean(), nullable=False),
    sa.Column('has_gst', sa.Boolean(), nullable=False),
    sa.Column('has_artisan_card', sa.Boolean(), nullable=False),
    sa.Column('intra_state_only', sa.Boolean(), nullable=False),
    sa.Column('name_check_passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisans_phone'), 'artisans', ['phone'], unique=True)
    op.create_table('staff_users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('cluster_id', sa.String(length=32), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=True)
    op.create_table('channel_status',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artisan_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.Enum('marketplace', 'ondc', 'gem', 'amazon', 'flipkart', 'meesho', 'whatsapp', name='channel'), nullable=False),
    sa.Column('signup_status', sa.Enum('not_started', 'taught', 'self_reported_done', 'connected', name='signupstatus'), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_seller_id', sa.String(length=120), nullable=True),
    sa.Column('last_export_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artisan_id', 'channel')
    )
    op.create_index(op.f('ix_channel_status_artisan_id'), 'channel_status', ['artisan_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artisan_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('notice_version', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_artisan_id'), 'consents', ['artisan_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artisan_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('desc_en', sa.Text(), nullable=True),
    sa.Column('desc_hi', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('category_map', sa.JSON(), nullable=False),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('technique', sa.String(length=120), nullable=True),
    sa.Column('dye_type', sa.String(length=80), nullable=True),
    sa.Column('loom_type', sa.String(length=80), nullable=True),
    sa.Column('time_taken_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dimensions', sa.String(length=120), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('is_fragile', sa.Boolean(), nullable=False),
    sa.Column('hsn_code', sa.String(length=12), nullable=True),
    sa.Column('cost_material', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labour_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_made_to_order', sa.Boolean(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('gi_claim', sa.String(length=120), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('colour_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_artisan_id'), 'products', ['artisan_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artisan_id', sa.String(length=32), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('chunks', sa.Integer(), nullable=False),
    sa.Column('received', sa.JSON(), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_artisan_id'), 'uploads', ['artisan_id'], unique=False)
    op.create_table('inventory_ledger',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('listings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.Enum('marketplace', 'ondc', 'gem', 'amazon', 'flipkart', 'meesho', 'whatsapp', name='channel'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('artifact_url', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'channel')
    )
    op.create_index(op.f('ix_listings_product_id'), 'listings', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.Enum('marketplace', 'ondc', 'gem', 'amazon', 'flipkart', 'meesho', 'whatsapp', name='channel'), nullable=False),
    sa.Column('external_order_id', sa.String(length=200), nullable=True),
    sa.Column('artisan_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('state', sa.Enum('placed', 'packed', 'shipped', 'delivered', 'settled', 'cancelled', name='orderstate'), nullable=False),
    sa.Column('fulfilment_model', sa.Enum('a_marketplace', 'b_aggregator', 'c_cluster_hub', name='fulfilmentmodel'), nullable=True),
    sa.Column('expected_settlement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('artisan_confirmed_payment', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_order_id')
    )
    op.create_index(op.f('ix_orders_artisan_id'), 'orders', ['artisan_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('size_variant', sa.String(length=40), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_orders_artisan_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_listings_product_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('inventory_ledger')
    op.drop_index(op.f('ix_uploads_artisan_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_products_artisan_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_consents_artisan_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_channel_status_artisan_id'), table_name='channel_status')
    op.drop_table('channel_status')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_index(op.f('ix_artisans_phone'), table_name='artisans')
    op.drop_table('artisans')
    op.drop_table('clusters')
    # ### end Alembic commands ###

    # Postgres does NOT drop an enum type when the last table using it goes away, and
    # autogenerate does not emit these. Without them, downgrade-then-upgrade dies on
    # "type \"channel\" already exists" — a failure that only shows up when you are already
    # rolling something back. `checkfirst` keeps this a no-op on a dialect with no native
    # enums (SQLite), so the migration stays runnable in a dev box.
    for name in ("channel", "signupstatus", "orderstate", "fulfilmentmodel"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
