#!/usr/bin/env python3
"""Generate the Android launcher icons and the native splash from the Kaarigar mark.

    python3 tools/make_icons.py            # writes into android/app/src/main/res
    python3 tools/make_icons.py --check    # draws to a scratch dir and prints sizes only

Why this is a script and not a folder of PNGs someone exported once:

  * `android/` is gitignored. The whole native project is regenerated by `npx cap add
    android`, which restores the stock Capacitor logo every time. Committed PNGs would be
    silently reverted by a command in our own README; a script in `app/tools/` survives it.
  * The mark is placeholder geometry (see src/ui/Mark.jsx). When a designer replaces it,
    the shape changes in two files and every one of the 26 rasters below is regenerated by
    one command instead of being re-exported by hand at five densities.

The mark is defined on the same 120x120 grid as Mark.jsx, and the two must agree — the
splash the artisan sees is this PNG for the first frame and the SVG immediately after, and
a mismatch shows up as a visible jump at the handover.

Everything is drawn at 8x and downsampled, because PIL has no anti-aliasing on strokes.
A 48px mdpi icon drawn directly is a staircase.
"""

import argparse
import os
from PIL import Image, ImageDraw

# --- the palette ------------------------------------------------------------------
# Must match `:root` / `[data-theme='forest']` in src/ui/styles.css. The launcher icon
# cannot follow the in-app theme — Android caches it at install time — so it is always the
# default palette, which is also why the splash config in capacitor.config.json is.
ACCENT = (156, 61, 36)  # #9c3d24 — clay
WHITE = (255, 255, 255)

SS = 8  # supersampling factor

# --- the mark, on a 120x120 grid (mirrors src/ui/Mark.jsx) -------------------------
LOZENGE = [(60, 34), (86, 60), (60, 86), (34, 60)]
CORE = [(60, 47), (73, 60), (60, 73), (47, 60)]
LIFT = [(44, 22), (60, 8), (76, 22)]
STROKE = 7.0

# The inked bounding box of the mark, stroke included — NOT the 120x120 grid.
#
# The grid has a lot of air in it (the loom on the splash fills that air; the icons have
# no loom). Fitting the icons to the grid instead of to this box is what made the first
# pass come out as a small glyph adrift in a green tile: the lozenge is 52 units wide in a
# 120-unit box, so "62% of the canvas" was really 27% of it.
MARK_L, MARK_T = 34 - STROKE / 2, 8 - STROKE / 2
MARK_R, MARK_B = 86 + STROKE / 2, 86 + STROKE / 2
MARK_W, MARK_H = MARK_R - MARK_L, MARK_B - MARK_T

# The loom behind the mark on the splash — the resting state of the animation in
# ui/Splash.jsx, so the still frame and the first animated frame are the same picture.
LOOM_AT = (30, 45, 60, 75, 90)
LOOM_FROM, LOOM_TO = 18, 102
LOOM_STROKE = 2.5
LOOM_ALPHA = 140  # ~0.55 opacity, matching .splash__warp in styles.css


def stroke(draw, pts, width, fill, closed=False):
    """A polyline with round caps and joins, which PIL does not do on its own."""
    path = list(pts) + ([pts[0]] if closed else [])
    draw.line(path, fill=fill, width=int(round(width)), joint="curve")
    r = width / 2
    for x, y in path:
        draw.ellipse((x - r, y - r, x + r, y + r), fill=fill)


def place(pts, scale, ox, oy):
    return [(x * scale + ox, y * scale + oy) for x, y in pts]


def draw_mark(draw, scale, ox, oy, colour):
    stroke(draw, place(LOZENGE, scale, ox, oy), STROKE * scale, colour, closed=True)
    draw.polygon(place(CORE, scale, ox, oy), fill=colour)
    stroke(draw, place(LIFT, scale, ox, oy), STROKE * scale, colour)


def fit_mark(n, fraction):
    """Scale and offset that centre the mark's ink in `fraction` of an n-pixel square."""
    scale = n * fraction / max(MARK_W, MARK_H)
    ox = (n - MARK_W * scale) / 2 - MARK_L * scale
    oy = (n - MARK_H * scale) / 2 - MARK_T * scale
    return scale, ox, oy


def draw_loom(draw, scale, ox, oy, colour):
    w = LOOM_STROKE * scale
    for v in LOOM_AT:
        stroke(draw, place([(v, LOOM_FROM), (v, LOOM_TO)], scale, ox, oy), w, colour)
        stroke(draw, place([(LOOM_FROM, v), (LOOM_TO, v)], scale, ox, oy), w, colour)


def canvas(w, h, bg):
    """An RGBA canvas at 8x. `bg=None` leaves it transparent (adaptive foregrounds)."""
    return Image.new("RGBA", (w * SS, h * SS), bg if bg else (0, 0, 0, 0))


def finish(img, w, h, flatten=None):
    out = img.resize((w, h), Image.LANCZOS)
    if flatten:
        bg = Image.new("RGB", (w, h), flatten)
        bg.paste(out, mask=out.split()[3])
        return bg
    return out


def icon_foreground(px):
    """Adaptive icon foreground: 108dp canvas, art kept inside the 66dp safe zone.

    Android crops this to a circle, a squircle or a rounded square depending on the OEM,
    and shows only the middle 72dp of the 108dp canvas. 60/108 keeps the mark inside that
    on every mask with a little room to spare, which matters because the tall axis here is
    the lifted chevron and clipping that off removes the one part of the mark that means
    anything.
    """
    img = canvas(px, px, None)
    d = ImageDraw.Draw(img)
    draw_mark(d, *fit_mark(px * SS, 60 / 108), WHITE)
    return finish(img, px, px)


def icon_legacy(px, round_mask):
    """Pre-Android-8 launcher icon: the mark on the accent, masked by us rather than the OS."""
    img = canvas(px, px, None)
    d = ImageDraw.Draw(img)
    n = px * SS
    if round_mask:
        d.ellipse((0, 0, n - 1, n - 1), fill=ACCENT)
    else:
        d.rounded_rectangle((0, 0, n - 1, n - 1), radius=n * 0.22, fill=ACCENT)
    # Tighter on the round mask: a shape sized for a square's corners overflows a circle
    # inscribed in the same box.
    draw_mark(d, *fit_mark(n, 0.56 if round_mask else 0.62), WHITE)
    return finish(img, px, px)


def splash(w, h):
    """The native splash: one still frame of ui/Splash.jsx with the animation finished.

    No wordmark. Rendering Devanagari here would mean bundling and shaping a font in a
    build script, and the React splash draws the word 300ms later in the artisan's own
    language anyway — which a baked-in PNG could never do.
    """
    img = canvas(w, h, ACCENT)
    d = ImageDraw.Draw(img, "RGBA")
    scale = min(w, h) * SS * 0.42 / 120
    ox = (w * SS - 120 * scale) / 2
    oy = (h * SS - 120 * scale) / 2
    draw_loom(d, scale, ox, oy, WHITE + (LOOM_ALPHA,))
    draw_mark(d, scale, ox, oy, WHITE)
    return finish(img, w, h, flatten=ACCENT)


# The adaptive icon's background layer is a flat colour, not a raster — the foreground PNG
# is the white mark on nothing. Written from here so the colour cannot drift away from the
# ACCENT the icons above are drawn on, and so it survives `npx cap add android` along with
# everything else this script owns.
#
# ⚠️ No double hyphen anywhere in that comment text. It is illegal inside an XML comment and
# aapt fails the entire resource merge on it, with an error that names the line but not the
# reason. Do not write the CSS custom properties by name in here.
LAUNCH_THEME_XML = """<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by app/tools/make_icons.py. Edit the script, not this file.
-->
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:background">@null</item>
    </style>

    <!--
      The launch theme: what is on screen between the icon tap and the WebView's first
      frame. This is the app's real first impression and Capacitor's template gets it
      wrong on any modern phone.

      The template sets `android:background` only, which is the pre-Android-12 mechanism.
      From API 31 the system owns that window and draws its own splash from the three
      attributes below. A theme that does not set them gets the platform default: the
      launcher icon on the theme colour, appearing only after a beat. That beat is why the
      splash looked like it started late instead of on the tap.

      Set, the Kaarigar mark is on the accent the instant the icon is pressed, and it hands
      over to the animated splash in src/ui/Splash.jsx. Same mark, same colour, no seam.

      `postSplashScreenTheme` is not optional: without it the activity keeps this theme
      after the splash and every screen in the app inherits the splash drawable as its
      window background.
    -->
    <style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/ic_launcher_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/ic_launcher_foreground</item>
        <item name="postSplashScreenTheme">@style/AppTheme.NoActionBar</item>
        <!-- Pre-API-31 fallback. Ignored on 12 and up. -->
        <item name="android:background">@drawable/splash</item>
    </style>
</resources>
"""

BACKGROUND_XML = """<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by app/tools/make_icons.py. Edit the script, not this file.

  The adaptive icon's background layer. The foreground (mipmap-*/ic_launcher_foreground.png)
  is the white Kaarigar mark with nothing behind it, so this colour is the icon.

  Matches the accent custom property in src/ui/styles.css and the SplashScreen
  backgroundColor in capacitor.config.json. It cannot follow the in-app theme, because
  Android caches launcher icons at install time, so it is always the default palette.
-->
<resources>
    <color name="ic_launcher_background">#%02X%02X%02X</color>
</resources>
"""


# density -> (legacy icon px, adaptive foreground px, portrait splash, landscape splash)
DENSITIES = {
    "mdpi": (48, 108, (320, 480), (480, 320)),
    "hdpi": (72, 162, (480, 800), (800, 480)),
    "xhdpi": (96, 216, (720, 1280), (1280, 720)),
    "xxhdpi": (144, 324, (960, 1600), (1600, 960)),
    "xxxhdpi": (192, 432, (1280, 1920), (1920, 1280)),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--res", default=None, help="path to android/app/src/main/res")
    ap.add_argument("--check", action="store_true", help="render to /tmp and report only")
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    res = args.res or os.path.join(here, "..", "android", "app", "src", "main", "res")
    res = "/tmp/kaarigar-icons" if args.check else os.path.abspath(res)

    if not args.check and not os.path.isdir(res):
        raise SystemExit(
            f"no res/ at {res}\n"
            "Run `npx cap add android` first — the native project is gitignored and is "
            "expected to be regenerated, which is the whole reason this is a script."
        )

    written = []

    def save(img, *parts):
        path = os.path.join(res, *parts)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        img.save(path)
        written.append((os.path.join(*parts), img.size))

    for density, (legacy, fg, port, land) in DENSITIES.items():
        save(icon_legacy(legacy, False), f"mipmap-{density}", "ic_launcher.png")
        save(icon_legacy(legacy, True), f"mipmap-{density}", "ic_launcher_round.png")
        save(icon_foreground(fg), f"mipmap-{density}", "ic_launcher_foreground.png")
        save(splash(*port), f"drawable-port-{density}", "splash.png")
        save(splash(*land), f"drawable-land-{density}", "splash.png")

    # The density-less fallback. Android falls back to drawable/ when it has no better
    # match, and Theme.SplashScreen in values/styles.xml points at exactly this one.
    save(splash(480, 320), "drawable", "splash.png")

    # The two XML resources that go with the rasters: the adaptive icon's flat background,
    # and the launch theme that decides whether the splash appears on the tap or a beat
    # after it. Both are regenerated by `npx cap add android` back to Capacitor's defaults,
    # which is why they are written from here rather than edited in place.
    for name, body in (
        ("ic_launcher_background.xml", BACKGROUND_XML % ACCENT),
        ("styles.xml", LAUNCH_THEME_XML),
    ):
        xml = os.path.join(res, "values", name)
        os.makedirs(os.path.dirname(xml), exist_ok=True)
        with open(xml, "w", encoding="utf-8") as fh:
            fh.write(body)
        written.append((f"values/{name}", None))

    for name, size in written:
        print(f"{name:44} {f'{size[0]}x{size[1]}' if size else 'flat colour'}")
    print(f"\n{len(written)} files -> {res}")


if __name__ == "__main__":
    main()
